### ISSUE TITLE
Choosing which display to stream from host example in windows sdk

### ISSUE THREAD

**Issue by pexproduction** [parsec-cloud/parsec-sdk#14]
Choosing which display to stream from host example in windows sdk with dual monitor would be great! Is there a way? without having to change the main display display settings in windows?

**Comment by chrisd1100** [comment]
This is coming in the next release, you'll be able to select the output in `ParsecHostConfig`. Additionally there will be support for multiple video streams in the same SDK connection.

**Comment by chrisd1100** [comment]
This has been implemented internally and will be made available in the upcoming release.
