### ISSUE TITLE
Question: Web: audio, video and container element requirements

### ISSUE THREAD

**Issue by mseeley** [parsec-cloud/parsec-sdk#17]
Parsec v3 requires `audio`, `video`, and `container` elements. The quick start guide doesn't indicate requirements for their DOM heirarchy.

The example shows `video` parented by `container`; but not `audio`. 

https://github.com/parsec-cloud/parsec-sdk/blob/f89cfe76277a6cd9e3f0042bfa1bf3ea5605e61e/examples/web/index.html#L15-L18

- Must `video` be parented by `container`? Or, is the only requirement that `container` and `video` be the same sized and positioned rectangles (with video behind container so not to interfere with event handling)?
- Any significance to `audio` _not_ being in the container?

Thanks!

**Comment by chrisd1100** [comment]
The `audio` element does not need any particular positioning in the DOM, it will be able to play/pause the audio stream from anywhere.

The SDK uses the `video` element to push the frames to and the `container` element to add input event listeners to. The intention here is that the `container` element would be the full window or `div` for the client area, and the `video` element can then be a child which can be letter-boxed or positioned within the greater client window.  If you have no need for letter-boxing then you could probably make the `container` element and `video` element the same.
