### ISSUE TITLE
Question: Web: client push input to Parsec

### ISSUE THREAD

**Issue by mseeley** [parsec-cloud/parsec-sdk#18]
Parsec v3 listens for keyboard events and determines side effects for a key press using keycode maps baked into the Parsec client.

Would you all be willing to consider the following:

- Pass a custom mapping of `event.keyCode` to `event.code`. For example, key events on some embedded platforms won't have the `event.code` or will have non-standard values. A client implementation can provide Parsec a `keyCode` to `code` mapping.
- Or, provide a hook for programmatically providing input. For example, a client implementation handle keyboard input manually then calling to Parsec instance with the name of the keys pressed or released.

Thanks for your feedback.

**Comment by chrisd1100** [comment]
By default the web SDK does not add event listeners to the DOM, but you can still call `clientSendMessage` to send arbitrary input messages to the host. These messages mimic the structs found in the C API, for instance a gamepad button message would look like:

```
parsec.clientSendMessage({
  'type': 5,  // MESSAGE_GAMEPAD_BUTTON
  'gamepadButton': {
    'button': 1  // GAMEPAD_BUTTON_B
    'pressed': true,
    'id': 1,  // User defined client-side gamepad ID
  }
});
```

All input messages can be sent this way, so if you want to add event listeners then send different keys than what the `handleInput` method will do, you could create your own lookup table then send a parsec keyboard message with your mapped value.

See: https://github.com/parsec-cloud/parsec-sdk/blob/master/sdk/parsec.h#L649-L654

**Comment by mseeley** [comment]
@chrisd1100 thanks a lot for this sample!

**Comment by olivmonnier** [comment]
Hi, i try to test the api with a simple test with the web example but nothing change. 
This is my test: 
```javascript
const container = _('.video-container');
container.style.display = 'block';
table.style.display = 'none';

// Parsec instance and client connection
const parsec = new Parsec(_('video'), _('audio'), container);
parsec.setLogCallback(arg => console.log(arg))

parsec.handleInput(parsec.Input.All);

parsec.clientConnect(sessionId, server.peer_id, '');

// My TEST
setInterval(() => {
  parsecInstance.clientSendMessage({
    type: 1,
    keyboard: {
      code: 4,
      mod: 0x0001,
      pressed: true
    }
  });
}, 3000)
```

Thanks a lot for your work and help.
