### ISSUE TITLE
const-ify the API

### ISSUE THREAD

**Issue by Eugeny** [parsec-cloud/parsec-sdk#20]
There are lots of `char *` arguments in the API, but it's very likely that these strings are never modified inside and if they are, there's no clear lifetime specified for them.

It's a good idea to change types to `const char *` where possible - this will simplify bindings a lot - e.g. Swift allows transparent bridging for `const char*` strings.

**Comment by chrisd1100** [comment]
This has been implemented internally and will be available in the next release.
