### ISSUE TITLE
Can't build iOS Swift project due to wrong framework name

### ISSUE THREAD

**Issue by ztepsa** [parsec-cloud/parsec-sdk#8]
Currently it's not possible to run iOS Swift project using `ParsecSDK` framework due to wrong name in `module.modulemap`.

Steps to reproduce:
1. create new iOS project (Swift)
2. add Parsec iOS framework
3. try to import parsec using `import Parsec`
4. observe Xcode throwing error `No such module 'Parsec'`

Since framework is named `ParsecSDK` we can easily fix this by manually updating name from `Parsec` to `ParsecSDK`. After fixing the project to import `ParsecSDK` instead of `Parsec` it's possible to build it.

**Comment by chrisd1100** [comment]
Solved in a73f72b.
